language: go
dist: bionic
go:
  - "1.7"
  - "1.8"
  - "1.9"
  - "1.10"
  - "1.11"
  - "1.12"
  - "1.13"
  - "1.14"
install:
  - make travis
script:
  - go test -coverprofile=coverage.txt
after_success:
  - bash <(curl -s https://codecov.io/bash)
